# Generated by Django 5.1.2 on 2024-10-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hadiths', '0006_remove_hadith_hadith_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith',
            name='narrator',
            field=models.CharField(choices=[('البخاري', 'البخاري'), ('مسلم', 'مسلم'), ('الترمذي', 'الترمذي'), ('النسائي', 'النسائي'), ('أبي داود', 'أبي داود'), ('ابن ماجه', 'ابن ماجه')], max_length=250),
        ),
    ]
